version: '3.9'

services:
  telegraf-esxi1:
    image: telegraf-ipmi:latest
    container_name: telegraf_esxi1
    restart: unless-stopped
    networks:
      - public
    environment:
      INFLUX_TOKEN: "D37pKSxAckN_OoHVpPNFHOi5kIQGMi2wMVHsvKDnOLzUsCcNQR68UU_Fwjto-u4dkoIjGgQ140zKVLe4j3VysA=="
    configs:
      - source: telegraf_conf
        target: /etc/telegraf/telegraf.conf

configs:
  telegraf_conf:
    file: ./telegraf.conf

networks:
  public:
    external: true
