version: '3.9'

services:
  telegraf-esxi:
    image: telegraf-ipmi:latest
    restart: unless-stopped
    networks:
      - public
    environment:
      HOST_NAME: "esxi2"
      INFLUX_TOKEN: "cvO4-qVvTQYE7ysNHMLDFY87s7ERe-vASvdFRF9g7DZyXeQsYS0kyAWE6ZqmM043TpG1mORlwvxGsD2RD94IhQ=="
      ESXI_HOST: "https://172.16.1.12/sdk"
      IPMI_HOST: "telegraf:66306494@lanplus(172.16.1.156)"
    configs:
      - source: telegraf_conf
        target: /etc/telegraf/telegraf.conf

configs:
  telegraf_conf:
    file: ./telegraf.conf

networks:
  public:
    external: true
