# password : 9sKiFEJauNsN
version: '3.9'

services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: always
    environment:
      WEBSOCKET_ENABLED: "false"  # WebSocket notifications.
    networks:
      - public
    volumes:
      - vaultwarden-data:/data
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=public"
        - "traefik.http.routers.vaultwarden_vaultwarden.entrypoints=websecure"
        - "traefik.http.routers.vaultwarden_vaultwarden.tls=true"
        - "traefik.http.routers.vaultwarden_vaultwarden.rule=Host(`vaultwarden.office.local`)"
        - "traefik.http.routers.vaultwarden_vaultwarden.service=vaultwarden_vaultwarden"
        - "traefik.http.services.vaultwarden_vaultwarden.loadbalancer.server.port=80"

networks:
  public:
    external: true

volumes:
  vaultwarden-data: